# fly.toml app configuration file generated for sola-sails on 2025-04-05T17:44:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sola-sails'
primary_region = 'sin'
console_command = '/rails/bin/rails console'

[build]

[env]
  THRUSTER_HTTP_PORT = '8080'
  THRUSTER_TARGET_PORT = '3000'

[deploy]
  release_command = './bin/rails db:prepare'

[processes]
  app = './bin/thrust ./bin/rails server'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 100

  [[http_service.checks]]
    grace_period = "60s"
    interval = "15s"
    method = "GET"
    path = "/up"
    protocol = "http"
    timeout = "10s"

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
